Update to Pivot 0.11.33 from Imply distribution 2.1.1

diff --git a/bin/pivot b/bin/pivot
--- a/bin/pivot
+++ b/bin/pivot
@@ -1,23 +1,17 @@
-#!/usr/bin/env node
+#!/bin/sh
 
-/*
- * Copyright 2015-2016 Imply Data, Inc.
- *
- * Licensed under the Apache License, Version 2.0 (the "License");
- * you may not use this file except in compliance with the License.
- * You may obtain a copy of the License at
- *
- *     http://www.apache.org/licenses/LICENSE-2.0
- *
- * Unless required by applicable law or agreed to in writing, software
- * distributed under the License is distributed on an "AS IS" BASIS,
- * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
- * See the License for the specific language governing permissions and
- * limitations under the License.
- */
+if command -v node > /dev/null 2>&1; then
+  NODE=`command -v node`
 
-var path = require('path');
-var fs   = require('fs');
-var lib = path.join(path.dirname(fs.realpathSync(__filename)), '../build/server/www.js');
+elif command -v nodejs > /dev/null 2>&1; then
+  NODE=`command -v nodejs`
 
-require(lib);
+else
+  echo "Could not find node or nodejs, please verify that it is installed.";
+  exit 1;
+fi
+
+# This is basically a platform independent way of doing `dirname `readlink -f $0` / `dirname `realpath $0`
+RUNJS=`"$NODE" -p "require('path').resolve(require('fs').realpathSync(process.argv[1]), '../../build/server/www.js')" "$0"`;
+
+exec "$NODE" "$RUNJS" "$@";
